FROM node:18-alpine

WORKDIR /app

COPY backend/Login/package*.json ./

# drpendances
RUN npm install

COPY backend/Login/ ./backend/

# Creer un utilisateur non-root
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 && \
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000

#CMD ["sh", "-c", "cd /app/backend && npm run dev"]
CMD [ "npx", "nodemon", "/app/backend/src/app.js" ]