FROM node:18-alpine

WORKDIR /app

COPY backend/package*.json ./

# les dependances
RUN npm ci --only=production

COPY backend/ ./backend/

# Créer un utilisateur non-root pour la secu
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 && \
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000

CMD ["node", "/app/backend/src/app.js"]